module.exports = {
  MODE: "development",
  PORT: 3005,
  BROWSER: "default",
  HOST: "localhost",
  HTTPS: false,
  BASE_PATH: "./",
  TRANSLATIONS_ENABLED: true,
  SERVICEWORKER_ENABLED: true,
  BUILD_PATH: "build",
  VIEWS_PATH: "views",
  PUBLIC_PATH: "public",
  SRC_PATH: "src",
  ASSETS_PATH: "assets",
  ASSETS_JS_PATH: "js",
  ASSETS_CSS_PATH: "css",
  ASSETS_IMG_PATH: "images",
  ASSETS_SVG_PATH: "icons",
  ASSETS_FONT_PATH: "fonts",
  GENERATE_SOURCEMAP: true,
  ASSET_IMG_INLINE_SIZE_LIMIT: 8192,
  ASSET_SVG_INLINE_SIZE_LIMIT: 8192,
  ANALYZE_BUNDLE: false,
};
