module.exports = {
  BUILD_FOLDER: "build",
  PUBLIC_FOLDER: "public",
  SRC_FOLDER: "src",
  ASSETS_FOLDER: "assets",
  ASSETS_JS: "js",
  ASSETS_CSS: "css",
  ASSETS_IMG: "images",
  ASSETS_SVG: "icons",
  ASSETS_FONT: "fonts",
  VIEWS_FOLDER: "views",
  PORT: 3001,
  ASSET_SVG_INLINE_SIZE_LIMIT: 8 * 1024,
  ASSET_IMG_INLINE_SIZE_LIMIT: 8 * 1024,
};
