const {
  BUILD_FOLDER,
  PUBLIC_FOLDER,
  SRC_FOLDER,
  ASSETS_FOLDER,
  ASSETS_JS,
  ASSETS_CSS,
  ASSETS_IMG,
  ASSETS_SVG,
  ASSETS_FONT,
  VIEWS_FOLDER,
} = require("./eofol");

const { resolve } = require("@eofol/eofol-dev-utils");

module.exports = {
  BUILD_PATH: resolve(BUILD_FOLDER),
  PUBLIC_PATH: resolve(PUBLIC_FOLDER),
  ENTRYPOINT_ROOT_PATH: resolve(SRC_FOLDER) + "/" + VIEWS_FOLDER + "/",
  ASSETS_BUILD_PATH: resolve(BUILD_FOLDER + "/" + ASSETS_FOLDER),
  ASSETS_INNER_PATH: "/" + ASSETS_FOLDER + "/",
  ASSETS_JS_PATH: ASSETS_JS,
  ASSETS_CSS_PATH: ASSETS_CSS,
  ASSETS_IMG_PATH: ASSETS_IMG,
  ASSETS_SVG_PATH: ASSETS_SVG,
  ASSETS_FONT_PATH: ASSETS_FONT,
};
